---
- name: test role module
  hosts: all

  tasks:
    - name: add workflow approve role
      awx.awx.role:
        controller_host: https://test-controller-hsaito-aap2.apps.acm-ansible-ocp-01.cee.ral3.lab.eng.rdu2.redhat.com/
        controller_username: ansible
        controller_password: changeme
        user: test
        workflows: wftest
        role: approval
        validate_certs: false

