---
- name: test role module
  hosts: 127.0.0.1

  tasks:
    - name: add workflow approve role
      awx.awx.role:
        controller_host: https://towerhost
        controller_username: ansible
        controller_password: changeme
        user: test
        role: approval

