---
- name: Check Condition
  hosts: all
  gather_facts: no
  tasks:
    - name: get Inventory id
      debug:
        var: tower_inventory_name
        
    - name:
      debug:
        var: epic

    - name: testing lookups
      debug:
        msg: "{{ lookup('env','username') }}"
             
    - debug:
        msg: "{{ lookup('env','ansible_user') }}"

    - debug:
        msg: "{{ lookup('env','ansible_password') }}"
        
    - debug:
        msg: "{{ ansible_user }}"
        
    - debug:
        msg: "{{ username }}"
